site_name: Sparkpost
repo_url: https://github.com/cividesk/com.cividesk.email.sparkpost
theme: material
markdown_extensions:
  - admonition
  - pymdownx.magiclink
pages:
- About: index.md
- Installation: install.md
- Bounce processing: bounce-processing.md
- Known issues: issues.md
- Supporting: supporting.md
